name: Mirror to Codeberg
on:
  push:
    branches: [main]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git remote add codeberg https://oauth2:${{ secrets.CODEBERG }}@codeberg.org/i-am-kiki/lipi.git
          git push codeberg main --force
